openapi: 3.0.0
info:
  description: |
    # Introduction
    This API is documented in **OpenAPI format**.

    # Basics
    * API calls have to be secured with HTTPS.
    * All data has to be submitted UTF-8 encoded.
    * The reply is either sent JSON encoded or as binary data for files.

    # Authentication
    **verify-u** API uses Basic Authentication with secret key as username only.

    Detailed information is provided at [Authentication](authentication)
  version: 1.0.0
  title: verify-u API
tags:
  - name: identifications
    description: Methods to retrieve identification details
paths:
  /identifications:
    get:
      tags:
        - identifications
      summary: identifications
      description: Returns the last 10 identifications as a list
      operationId: getIdentificationsList
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    age_permission:
                      type: boolean
                      description: Permission to access age of customer
                      example: true
                    date_created:
                      type: string
                      format: timestamp
                      description: Creation date
                      example: 1589550707
                    full_name_permission:
                      type: boolean
                      description: Permission to access full name of customer
                      example: true
                    gender_permission:
                      type: boolean
                      description: Permission to access gender of customer
                      example: true
                    id:
                      type: string
                      description: Identification ID
                      example: b8532da4-b9e4-439d-aaae-10cc750579bb	
                    passport_permission:
                      type: boolean
                      description: Permission to access ID document data of customer
                      example: true
                    state:
                      type: string
                      description: Identification state parameter
  "/identifications/{id}":
    get:
      tags:
        - identifications
      summary: identifications/{id}
      description: Returns client profile data for a single identification
      operationId: getIdentificationById
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the identification
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                    nullable: true
                    description: Address
                    example: 40 Mill Road, NEWPORT, NP14 0CV
                  date_created:
                    type: string
                    format: timestamp
                    description: Date created
                    example: 1589550707
                  date_of_birth:
                    type: string
                    nullable: true
                    format: date
                    description: Date of birth
                    example: 07.10.1978
                  gender:
                    type: string
                    nullable: true
                    description: Gender
                    example: M
                  id_channel_id:
                    type: string
                    format: uuid
                    description: Id Channel ID
                    example: 42b45084-a441-4e48-88e1-8424cae60f3b
                  id_document:
                    type: object
                    nullable: true
                    description: Id Document front
                    properties:
                      country:
                        type: string
                        nullable: true
                        description: Issuing country
                        example: UK
                      date_created:
                        type: string
                        nullable: true
                        format: timestamp
                        description: Date created
                        example: 1589550707
                      document_type:
                        type: string
                        nullable: true
                        description: Document type
                        example: ID_CARD
                      expiration_date:
                        type: string
                        nullable: true
                        format: date
                        description: Date of expiration
                        example: 30.05.2028
                      issue_date:
                        type: string
                        nullable: true
                        format: date
                        description: Date of issue
                        example: 30.05.2018
                      last_updated:
                        type: string
                        nullable: true
                        format: timestamp
                        description: Last updated
                        example: 1589550707
                      mrz:
                        type: string
                        nullable: true
                        description: Machine-readable zone of document
                        example: P<GBRDOE<<JOHN<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<9138625549GBR4503093M1601013<<<<<<<<<<<<<<00
                      number:
                        type: string
                        nullable: true
                        description: Document number
                        example: C1544JKK40
                  id_document_back:
                    type: object
                    nullable: true
                    description: Id Document back
                    properties:
                      country:
                        type: string
                        nullable: true
                        description: Issuing country
                        example: UK
                      date_created:
                        type: string
                        nullable: true
                        format: timestamp
                        description: Date created
                        example: 1589550707
                      document_type:
                        type: string
                        nullable: true
                        description: Document type
                        example: ID_CARD
                      expiration_date:
                        type: string
                        nullable: true
                        format: date
                        description: Date of expiration
                        example: 30.05.2028
                      issue_date:
                        type: string
                        nullable: true
                        format: date
                        description: Date of issue
                        example: 30.05.2018
                      last_updated:
                        type: string
                        nullable: true
                        format: date
                        description: Date of issue
                      mrz:
                        type: string
                        nullable: true
                        description: Machine-readable zone of document
                      number:
                        type: string
                        nullable: true
                        description: Document number
                        example: C1544JKK40
                  id_document_secondary:
                    type: object
                    nullable: true
                    description: Id Document secondary
                    properties:
                      country:
                        type: string
                        nullable: true
                        description: Issuing country
                        example: UK
                      date_created:
                        type: string
                        nullable: true
                        format: timestamp
                        description: Date created
                        example: 1589550707
                      document_type:
                        type: string
                        nullable: true
                        description: Document type
                        example: RESIDENCE_PERMIT
                      expiration_date:
                        type: string
                        nullable: true
                        format: date
                        description: Date of expiration
                        example: 30.05.2028
                      issue_date:
                        type: string
                        nullable: true
                        format: date
                        description: Date of issue
                        example: 30.05.2018
                      last_updated:
                        type: string
                        nullable: true
                        format: date
                        description: Date of issue
                      mrz:
                        type: string
                        nullable: true
                        description: Machine-readable zone of document
                      number:
                        type: string
                        nullable: true
                        description: Document number
                        example: C1544JKK40
                  first_name:
                    type: string
                    nullable: true
                    description: First name
                    example: John
                  last_name:
                    type: string
                    nullable: true
                    description: Last name
                    example: Doe
                  last_updated:
                    type: string
                    format: timestamp
                    description: Last updated
                    example: 1589550707
                  primary_id_document_number:
                    type: string
                    nullable: true
                    description: Primary ID document number
                    example: C1544JKK40
                  rejected:
                    type: boolean
                    description: Rejected
                    example: true
                  rejection_cause:
                    type: string
                    nullable: true
                    description: Rejection cause
                    example: Photo did not match client
                  state:
                    type: string
                    description: State
                    example: client_reference_id:940af6f8-1180-4f0c-975b-cba770087277
        "404":
          description: Identification not found
        "500":
          description: Error
security:
  - basicAuth: []
servers:
  - url: https://verify-u.com/api
  - url: http://verify-u.com/api
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic