swagger: "2.0"
info:
  description: |
    # Introduction
    This API is documented in **OpenAPI format**.

    # Basics
    * API calls have to be secured with HTTPS.
    * All data has to be submitted UTF-8 encoded.
    * The reply is either sent JSON encoded or as binary data for files.

    # Authentication
    **verify-u** API uses Basic Authentication with secret key as username only.

    Detailed information is provided at [Authentication](authentication)
  version: 1.0.0
  title: verify-u API
tags:
  - name: identifications
    description: "Methods to retrieve identification details"
  - name: documents
    description: ""
schemes:
  - https
  - http
paths:
  /identifications:
    $ref: paths/identifications.yaml
  /identifications/{id}:
    $ref: paths/identifications_id.yaml
  /identifications/iddocument/{id}:
    $ref: paths/identifications_iddocument_id.yaml
  /identifications/video/{id}:
    $ref: paths/identifications_video_id.yaml
  /identifications/esign/{id}:
    $ref: paths/identifications_esign_id.yaml
  /documents/create:
    $ref: paths/documents_create.yaml
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []

host: verify-u.com
basePath: /api
