openapi: 3.0.0
info:
  description: |
    # Introduction
    This API is documented in **OpenAPI 3.0 format**.

    This API
    * enables a user to retrieve a list of the last 10 identifications
    * enables a user to retrieve profile data of a client's identification

    # Basics
    * API calls have to be secured with HTTPS.
    * All data has to be submitted UTF-8 encoded.
    * The reply is sent JSON encoded.

    # Authentication
    **verify-u** API uses Basic Authentication with secret key as username only.

    Detailed information is provided at [Authentication](authentication)
  version: 1.0.0
  title: verify-u API
tags:
  - name: identifications
    description: Methods to retrieve identification details
paths:
  /identifications:
    $ref: paths/identifications.yaml
  /identifications/{id}:
    $ref: paths/identifications_id.yaml
security:
  - basicAuth: []
servers:
  - url: https://verify-u.com/api  
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
